### ISSUE TITLE
NPE exception in Reclipse

### ISSUE THREAD

**Issue by snowball77** [ReEng/reclipse-emf#1]
Jure reported:

Hi!

Sometimes, when running Rclipse, nullpointer exception is thrown (see 
stacktrace).
Please fix this. Probably only null-check is needed in compare function.

Cheers, Jure

java.lang.NullPointerException
     at java.lang.String.compareTo(String.java:1139)
     at 
org.reclipse.structure.specification.util.ContainmentWeightedTriggerChooser$1.compare(ContainmentWeightedTriggerChooser.java:73)
     at 
org.reclipse.structure.specification.util.ContainmentWeightedTriggerChooser$1.compare(ContainmentWeightedTriggerChooser.java:1)
     at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
     at java.util.TimSort.sort(TimSort.java:189)
     at java.util.TimSort.sort(TimSort.java:173)
     at java.util.Arrays.sort(Arrays.java:659)
     at java.util.Collections.sort(Collections.java:217)
     at 
org.reclipse.structure.specification.util.ContainmentWeightedTriggerChooser.getTrigger(ContainmentWeightedTriggerChooser.java:66)
     at 
org.reclipse.structure.specification.util.TriggerManager.initialize(TriggerManager.java:119)
     at 
org.reclipse.structure.specification.util.TriggerManager.<init>(TriggerManager.java:67)
     at 
org.reclipse.structure.specification.util.TriggerManager.<init>(TriggerManager.java:73)
     at 
org.reclipse.structure.inference.strategy.BottomUpStrategy.<init>(BottomUpStrategy.java:44)
     at 
org.reclipse.structure.inference.InferenceEngine.start(InferenceEngine.java:133)
     at 
org.reclipse.structure.inference.DetectPatternsJob.start(DetectPatternsJob.java:100)
     at 
org.fujaba.commons.console.AbstractProcessConsoleJob.run(AbstractProcessConsoleJob.java:109)
     at 
eu.cloudscaleproject.env.staticspotter.alternatives.ConfigAlternative.doRun(ConfigAlternative.java:108)
     at 
eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative$1.run(AbstractConfigAlternative.java:96)
     at 
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
     at 
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
     at 
eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative.run(AbstractConfigAlternative.java:91)
     at 
eu.cloudscaleproject.env.toolchain.ui.ConfigEditorView$AlternativeRunJob.run(ConfigEditorView.java:270)
     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by snowball77** [comment]
I do not think that a null check will help as there should be no null strings worked upon there. However, a better check for the right arguments would already help and give a more useful error message.

**Comment by jurepolutnik** [comment]
Last version available on the nightly repo does not include this patch...
Please check this.

https://sdqweb.ipd.kit.edu/eclipse/reclipse/nightly

**Comment by snowball77** [comment]
How do you know? From the time stamp the build was done right after the commit mentioned here? Or do you mean it is included, but does not work?

**Comment by jurepolutnik** [comment]
hm, yes, the time stamp is ok. However, looking into sources, it does not include this patch. don't know why.

**Comment by snowball77** [comment]
I got it, the student committed the patch to a SVN tag folder instead of the trunk. I committed it to trunk too now. Lets see whether the build gets through

**Comment by snowball77** [comment]
No, it did not. The buckminster config was still wrong. Hope it is correct now

**Comment by snowball77** [comment]
It went through now. AFAIK, the patch should now be part of the build.
